# site settings
title: Abhilash
subtitle: Shah
email: 98abhilash@gmail.com
description: A Machine Learning Engineer <br /> and a life-long learner.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:  
city: Mumbai
state: Maharashtra
zip_code: 
country: India
phone: +91-8097062698

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/98abhilash
  GitLab:
  Google: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/98abhilash/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
